### ISSUE TITLE
Unity 2021.3

### ISSUE THREAD

**Issue by danieldownes** [joshcamas/prefab-library#1]
I have only just discovered this asset after it being recommended in this video:
https://www.youtube.com/watch?v=qrGUoSWSPc8

However I tried to load it into 2021.3 (URP on), and not of the prefabs are rendered:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/1720388/211608698-4d19196f-e342-475a-a458-e1edcf371e5f.png">

Notice the scrollbar. Also if I press refresh then I see assets that are in the current view do render, but when I scroll then further prefabs do not render.

**Comment by joshcamas** [comment]
Greetings, I'll take a look at this! I think I see the issue. This public version of the tool uses unity's asset preview, which is asynchronous. I'll make it correctly support it.

**Comment by joshcamas** [comment]
Alright, this should have been fixed! I'll close this once I have confirmation that it works for you
